# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vedant Dwivedi
email: "vedant.dwivedi55@gmail.com"
description: >
  I am an altruist by nature and a cogent at work, a datascientist by profession, looking to share my endeavour, as well as keep an organized list of projects in one place.
about_me: >
  I'm a fulltime working employee at asia's largest startup, i have been working in few domains like DevSecOps, machine Learning Models, Blockchain, Python but always the forte was to solve the problem and bring the best solution,
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vedantdwivedi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linked_in_link: "https://www.linkedin.com/in/vedant-dwivedi-60286b10a/"
github_link: "https://github.com/Vedantdwivedi"
twitter_username: ""
google_analytics_id: 'UA-117297510-1'
select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: :nested

gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
